version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - insurance_app_network

  web-graphql-api:
    container_name: web-graphql-api
    image: 'ruby:3.2.2'
    working_dir: /app
    volumes:
      - .:/app
      - ruby_gems:/usr/local/bundle
    ports:
      - "4000:4000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: bash -c "rm -f tmp/pids/server.pid && bin/setup && bundle exec rails s -b '0.0.0.0' -p 4000"
    networks:
      - insurance_app_network

volumes:
  ruby_gems:

networks:
  insurance_app_network:
    name: insurance_app_network
    external: true