version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres-api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - insurance_app_network

  web-api:
    build: .
    container_name: web-api
    working_dir: /app
    depends_on:
      - postgres
    command: bash -c "rm -f tmp/pids/server.pid && bin/setup && bundle exec rails s -p 5000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      UID: ${UID}
      GID: ${GID}
    user: "${UID}:${GID}"
    entrypoint: ./entrypoint.sh
    networks:
      - insurance_app_network

volumes:
  rubygems:
  pgdata:

networks:
  insurance_app_network:
      