version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres-api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - insurance_app_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - insurance_app_network

  web-api:
    container_name: web-api
    build:
      context: .
    working_dir: /app
    volumes:
      - .:/app
      - ruby_gems:/usr/local/bundle
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - rabbitmq
    command: bash -c "rm -f tmp/pids/server.pid && bin/setup && bundle exec rails s -p 5000 -b '0.0.0.0'"
    networks:
      - insurance_app_network

volumes:
  ruby_gems:
  pgdata:

networks:
  insurance_app_network:
      